### ISSUE TITLE
Stop using Google Analytics

### ISSUE THREAD

**Issue by TheOPtimal** [jonerrr/dababywebsite#1]
Google Anal Tittycks is cringe. Stop using cring on your website or at least use less cring anal tittycks service like [Plausible](https://github.com/plausible/analytics), or just stop using anal tittycks services completely.

Also consider replacing Sentry with [GlitchTip](https://glitchtip.com/), you can keep using the same SDKs for that.

**Comment by Gowixx** [comment]
cry about it

**Comment by jonerrr** [comment]
ill use cf
